project:
  type: website
  output-dir: docs
  resources:
    - images/**
  render:
    - index.qmd
    - contact.qmd

website:
  title: Southern Clarity New Zealand
  description: "Southern Clarity is a New Zealand-based company specialising in reproducible workflows and data science solutions. We are passionate about helping clients achieve clarity and insight from their data, enabling informed decisions and innovation."
  favicon: favicon.ico
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/southern-clarity-nz
        aria-label: LinkedIn
  page-footer:
    center: "© 2026 Southern Clarity NZ LTD. All rights reserved."

format:
  html:
    theme: default
    css: blog.css
    include-after-body: theme-toggle.js
    toc: false
